package/rcw: Delete rcw.hash
Fixes build error:
ERROR: No hash found for rcw-LSDK-19.09.tar.gz

Fixes: e4f52b177f67 ("Merge remote-tracking branch 'openil/master'")
Signed-off-by: Vladimir Oltean <olteanv@gmail.com>